baseurl = "https://berlinlokalzeit.de"
title = "#berlin_lokal_zeit"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "My Name"
pygmentsUseClasses = true
pygmentsCodefences = true

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = false

[taxonomies]
tag = "tags"

[params]
mainSections = [ "post" ]
intro = true
headline = "#berlin​↦​lokal​↦​zeit"
#description = "collaborative project"
#twitter = "https://twitter.com/XXX"
#facebook = "https://www.facebook.com/username"
#email = "XXX@example.com"
opengraph = true
#shareTwitter = true
#rss = true
#shareFacebook = true
dateFormat = "Mon, Jan 2, 2006"
readingTime = false
readingTimeText = "Estimated reading time:"

  [params.plausibleAnalytics]
  domain = ""
  serverURL = ""

[permalinks]
post = "/:year/:month/:day/:filename/"

[[menu.main]]
name = "Zum Projekt"
url = "/page/about/"
weight = 1

[[menu.main]]
name = "Ausstellung"
url = "/page/exhibition/"
weight = 3

[[menu.main]]
name = "Events"
url = "/project/"
weight = 4

[[menu.main]]
name = "Teilnehmer"
url = "/page/participants/"
weight = 5

[[menu.main]]
name = "Archiv"
url = "/page/archiv/"
weight = 6

[[menu.main]]
name = "Live"
url = "/page/telegram/"
weight = 8

[[menu.main]]
name = "Kontakt"
url = "/page/contact/"
weight = 9

