baseurl = "https://example.com/"
title = "#berlin_lokal_zeit"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "My Name"
pygmentsUseClasses = true
pygmentsCodefences = true

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = false

[author]
name = "Dietmar Offenhuber"
profile = ""

[taxonomies]
tag = "tags"

[params]
mainSections = [ "post" ]
intro = true
headline = "#berlin_lokal_zeit"
description = "collaborative project ..."
twitter = "https://twitter.com/XXX"
facebook = "https://www.facebook.com/username"
email = "XXX@example.com"
opengraph = true
shareTwitter = true
rss = true
shareFacebook = true
dateFormat = "Mon, Jan 2, 2006"
readingTime = false
readingTimeText = "Estimated reading time:"

  [params.plausibleAnalytics]
  domain = ""
  serverURL = ""

[permalinks]
post = "/:year/:month/:day/:filename/"

[[menu.main]]
name = "Blog"
url = "/post/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/project/"
weight = 2

[[menu.main]]
name = "Contact"
url = "/page/contact/"
weight = 3

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 4

