baseurl = "https://berlinlokalzeit.de"
title = "berlin_lokal_zeit"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "My Name"
pygmentsUseClasses = true
pygmentsCodefences = true
author = "berlin_lokal_zeit"

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = false

[taxonomies]
tag = "tags"

[params]
mainSections = [ "post" ]
intro = true
headline = "berlin​_​lokal​_​zeit"
summary = "#BERLIN_LOKAL_ZEIT ist ein partizipatives Projekt Stadtbeobachtungen während der Pandemie einzufangen und gemeinsam zu reflektieren."
#description = "#BERLIN_LOKAL_ZEIT ist ein partizipatives Projekt, das zum Ziel hat, Erfahrung des alltäglichen Lebens in der Stadt während der Pandemie einzufangen und gemeinsam zu reflektieren. Welche Phänomene treten auf, wie verändern sie sich und unsere Haltung zu ihnen im Laufe der Zeit?"
facebook = "https://www.facebook.com/groups/644335199595125"
telegram = "https://t.me/berlinlokalzeit"
instagram = "https://www.instagram.com/explore/tags/berlinlokalzeit/"
soundcloud = "https://radio.aporee.org"
email = "kontakt@clb-berlin.de"
opengraph = true
shareTwitter = true
#rss = true
shareFacebook = true
dateFormat = "Mon, Jan 2, 2006"
readingTime = false
readingTimeText = "Estimated reading time:"

  [params.plausibleAnalytics]
  domain = ""
  serverURL = ""

[permalinks]
post = "/:year/:month/:day/:filename/"

[[menu.main]]
name = "Zum Projekt"
url = "/page/about/"
weight = 1

[[menu.main]]
name = "Ausstellung"
url = "/page/exhibition/"
weight = 3

[[menu.main]]
name = "Events"
url = "/project/"
weight = 4

[[menu.main]]
name = "Teilnehmer"
url = "/page/participants/"
weight = 5

[[menu.main]]
name = "Archiv"
url = "/page/archiv/"
weight = 6

[[menu.main]]
name = "Live"
url = "/page/telegram/"
weight = 8



